server: 
  port: 8080  # 서버가 사용할 포트 번호를 8080으로 설정합니다. 웹 애플리케이션에 접근할 때 기본 HTTP 포트를 사용합니다.
  servlet:
    encoding:
      charset: utf-8  # 서블릿의 응답과 요청 인코딩을 UTF-8로 설정합니다.
      force: true  # 요청과 응답에 대해 이 인코딩을 강제로 사용하도록 설정합니다.

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/  # JSP 파일이 위치한 디렉토리의 접두사를 설정합니다.
      suffix: .jsp  # 뷰 이름에 자동으로 추가될 파일 확장자를 설정합니다.
  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL  # 데이터베이스 연결을 위한 URL을 설정합니다.
    driver-class-name: org.h2.Driver  # JDBC 드라이버 클래스를 설정합니다.
    username: sa  # 데이터베이스 연결을 위한 사용자 이름을 설정합니다.
    password: ''  # 데이터베이스 연결을 위한 비밀번호를 설정합니다. 여기서는 비밀번호를 빈 문자열로 설정했습니다.

  h2:
    console:
      enabled: true  # H2 데이터베이스 콘솔을 활성화합니다.

  output:
    ansi:
      enabled: always  # 콘솔 출력에 ANSI 색상 코드를 사용할 수 있도록 설정합니다.
      
#mybatis 설정 부분 입니다.   
mybatis: 
  mapper-locations:
    - classpath:mapper/**/*.xml  # MyBatis 매퍼 파일 위치를 설정합니다. **는 모든 디렉토리, *.xml은 모든 XML 파일을 의미합니다.
  configuration:
    map-underscore-to-camel-case: true  # 데이터베이스의 언더스코어 네이밍(예: column_name)을 자바의 카멜케이스 네이밍(예: columnName)으로 매핑합니다.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로깅 구현체를 설정합니다. 이 설정을 통해 콘솔에 SQL 로그를 출력합니다.

logging:
  level:
    org.apache.ibatis: DEBUG  # MyBatis 로깅 레벨을 DEBUG로 설정하여, 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력합니다.
    
    